services:
  paddle:
    build:
      context: .
      dockerfile: Dockerfile.paddle
    image: paddleocr-api # must be a single line, not a nested block
    container_name: paddle
    ports:
      - "8866:8866"

  ocr-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocr-service
    ports:
      - "8080:8080"
    depends_on:
      - paddle
